{{- if .Values.validator.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: substrate-secrets
  labels:
    app: substrate
type: Opaque
data:
{{- range $node, $keys := .Values.validator.secrets }}
{{- range $keytype, $value := $keys }}
  {{ $node }}-{{ $keytype }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
